### ISSUE TITLE
Minecraft Block Limit reached

### ISSUE THREAD

**Issue by ghost** [MJRLegends/MJRLegendsLib#18]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FutureMC (future-mc-0.1.13.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.239.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 12/31/19 10:03 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:999)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_575_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:999)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_575_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1299318896 bytes (1239 MB) / 3892314112 bytes (3712 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                        | Signature                                |
	|:----- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | micdoodlecore       |                   | minecraft.jar                                 | None                                     |
	| LCH   | futuremccore        | 0.1.12            | minecraft.jar                                 | None                                     |
	| LCH   | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | abyssalcraft        | 1.9.15            | AbyssalCraft-1.12.2-1.9.15 (1).jar            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | aoa3                | 3.1.2.b           | AoA3-3.1.2.b.jar                              | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.239         | GalacticraftCore-1.12.2-4.0.2.239.jar         | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.239         | Galacticraft-Planets-1.12.2-4.0.2.239.jar     | None                                     |
	| LCH   | asmodeuscore        | 0.0.12            | AsmodeusCore-1.12.2-0.0.12.jar                | None                                     |
	| LCH   | atum                | 2.0.16            | Atum-1.12.2-2.0.16.jar                        | None                                     |
	| LCH   | casinocraft         | v06               | CasinoCraft_1.12.2_v06.jar                    | None                                     |
	| LCH   | chaotica            | 4.8.5             | Chaotica_v4.8.51fixed[1.12.2].jar             | None                                     |
	| LCH   | ctm                 | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
	| LCH   | customnpcs          | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar               | None                                     |
	| LCH   | erebus              | 1.0.31            | Erebus-1.0.31.jar                             | None                                     |
	| LCH   | mjrlegendslib       | 1.12.2-1.1.9      | MJRLegendsLib-1.12.2-1.1.9.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | zollerngalaxy       | 2.0.8             | ZollernGalaxy-1.12.2-v2.0.8.jar               | None                                     |
	| LCH   | extraplanets        | 1.12.2-0.6.0      | ExtraPlanets-1.12.2-0.6.0.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | minecraftfuture     | 0.1.13            | future-mc-0.1.13.jar                          | None                                     |
	| LCH   | galaxyspace         | 2.0.11            | GalaxySpace-1.12.2-2.0.11.jar                 | None                                     |
	| LCH   | incontrol           | 3.9.16            | incontrol-1.12-3.9.16.jar                     | None                                     |
	| LCH   | moreplanets         | 2.0.22            | More-Planets-1.12.2-2.0.22-GC238.jar          | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LCH   | moreplayermodels    | 1.12.2            | MorePlayerModels_1.12.2-(05Dec19).jar         | None                                     |
	| LCH   | neat                | 1.4-17            | Neat+1.4-17.jar                               | None                                     |
	| LCH   | patchouli           | 1.0-20            | Patchouli-1.0-20.jar                          | None                                     |
	| LCH   | supertnt            | 1.0.1             | SuperTNT-1.12.2-1.0.1.jar                     | None                                     |
	| LCH   | theaurorian         | 1.12.2-Beta       | theaurorian-1.12.2-beta-dec2919.jar           | None                                     |
	| LCH   | thecrystallia       | 1.0.8             | TheCrystallia+1.0.9+[1.12.2].jar              | None                                     |
	| LCH   | twilightforest      | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCH   | xaerominimap        | 1.19.5            | Xaeros_Minimap_1.19.5_Forge_1.12.jar          | None                                     |
	| LCH   | xaeroworldmap       | 1.5.2             | XaerosWorldMap_1.5.2_Forge_1.12.jar           | None                                     |
	| LCH   | thebetweenlands     | 3.5.4             | TheBetweenlands-3.5.4-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.239.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7263' Renderer: 'Intel(R) UHD Graphics 630'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 26.20.100.7263, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz

**Comment by MJRLegends** [comment]
Not a bug or a error you should be reporting, you have reached minecraft blocks limit remove mods to get under this limit or add just enough ids mod
